filebeat.inputs:
- type: log 
  enabled: true
  fields:
    type: condor
  paths:
    - /data2/atlpan/condor_logs/*/grid.*.out
  multiline:
    pattern: '---- (.*?) ----'
    negate: true
    match: after
  ignore_older: 2h
output.logstash:
  hosts: ["aipanda012:5044", "aipanda019:5044"]
  worker: 4
  bulk_max_size : 8192
  loadbalance: true
  compression_level: 3
  index: condorlogs
logging.level: debug
logging.to_files: true
logging.to_syslog: false
logging.files:
  path: /var/log/filebeat
  name: filebeat.log
  keepfiles: 7
  permissions: 0644
  rotateeverybytes: 10485760