filebeat.inputs:
- type: log 
  enabled: false
  fields:
    type: condor
  paths:
#    - /data2/atlpan/condor_logs/*/grid.*.out
     - /data2/atlpan/condor_logs/disabled
  multiline:
    pattern: '---- (.*?) ----'
    negate: true
    match: after
output.logstash:
  hosts: ["aipanda012:5044", "aipanda019:5044"]
  worker: 10
  bulk_max_size : 8192
  loadbalance: true
  compression_level: 0
  index: condorlogs
logging.level: info
logging.to_files: true
logging.to_syslog: false
logging.files:
  path: /var/log/filebeat
  name: filebeat.log
  keepfiles: 7
  permissions: 0644
  rotateeverybytes: 10485760