filebeat:
  prospectors:
    -
      #########panda_harvester_stderr#########
      paths:
        - /var/log/harvester/panda_harvester_stderr.log
      input_type: log
      fields:
        type:  harvester_stderr
      multiline.pattern: '#####START#####'
      multiline.negate: true
      multiline.match: after
      multiline.flush_pattern: '#####END#####'
      include_lines: ['#####START#####']
  #  -
  #    #########panda-submitter.log#########
  #    paths:
  #      - /var/log/harvester/panda-submitter.log
  #    input_type: log
  #    fields:
  #      type: panda_submitter

  registry_file: /var/lib/filebeat/registry

output.logstash:
  hosts: ["aipanda145"]
  worker: 4
  bulk_max_size : 8192
  #loadbalance: true
  compression_level: 3
  index: harvesterlogs

logging:
  level: debug

  to_files: true

  to_syslog: false

  files:
    path: /var/log/filebeat
    name: filebeat.log
    rotateeverybytes: 10485760 # = 10MB
