filebeat:
  prospectors:
    -
      #########panda_harvester_stderr#########
      paths:
        - /var/log/harvester/panda_harvester_stderr.log
      input_type: log
      fields:
        type:  harvester_stderr
      multiline.pattern: '#####START#####'
      multiline.negate: true
      multiline.match: after
      multiline.flush_pattern: '#####END#####'
      include_lines: ['#####START#####']
  #  -
  #    #########panda-submitter.log#########
  #    paths:
  #      - /var/log/harvester/panda-submitter.log
  #    input_type: log
  #    fields:
  #      type: panda_submitter

  registry_file: /var/lib/filebeat/registry

output.logstash:
  hosts: ["aipanda145"]
  worker: 4
  bulk_max_size : 8192
  #loadbalance: true
  compression_level: 3
  index: harvesterlogs

logging.level: info
logging.to_files: true
logging.to_syslog: false
logging.files:
  path: /var/log/filebeat
  name: filebeat.log
  keepfiles: 7
  permissions: 0644
  rotateeverybytes: 10485760
