input {
  jdbc {
    jdbc_driver_library => "/opt/ojdbc8.jar"
    jdbc_driver_class => "Java::oracle.jdbc.OracleDriver"
    jdbc_connection_string => "CONNECTION_STRING"
    jdbc_user => "USER"
    jdbc_password => "PASSWORD"
    id => "c"
    type => "worker_node_gpus"

    schedule => "*/5 * * * *" 



    statement => "
SELECT
  NVL(wng.SITE, 'UNKNOWN')                  AS SITE,
  NVL(wng.HOST_NAME, 'UNKNOWN')             AS HOST_NAME,
  NVL(wng.VENDOR, 'UNKNOWN')                AS VENDOR,
  NVL(wng.MODEL, 'UNKNOWN')                 AS MODEL,

  NVL(wng.COUNT, -1)                        AS COUNT_PER_HOST,

  NVL(wng.FRAMEWORK, 'UNKNOWN')             AS FRAMEWORK,
  NVL(wng.VRAM, -1)                         AS VRAM,
  NVL(wng.ARCHITECTURE, 'UNKNOWN')          AS ARCHITECTURE,
  NVL(wng.FRAMEWORK_VERSION, 'UNKNOWN')     AS FRAMEWORK_VERSION,
  NVL(wng.DRIVER_VERSION, 'UNKNOWN')        AS DRIVER_VERSION,

  NVL(
    TO_CHAR(CAST(wng.LAST_SEEN AS TIMESTAMP),
            'YYYY-MM-DD HH24:MI:SS.FF6'),
    'UNKNOWN'
  ) AS LOG_TS,

  NVL(wnq.PANDA_QUEUE, 'UNKNOWN')            AS PANDA_QUEUE

FROM ATLAS_PANDA.WORKER_NODE_GPUS wng
JOIN ATLAS_PANDA.WORKER_NODE_QUEUE wnq
  ON wng.SITE = wnq.SITE
 AND wng.HOST_NAME = wnq.HOST_NAME
    "
  }
}

filter {
if [type] == "worker_node_gpus" {
  mutate {
    rename => { "log_ts" => "timestamp" }
    add_field => {
      "doc_key" => "%{site}-%{host_name}-%{panda_queue}-%{type}"
    }
  }
mutate {
  convert => { "clock_speed" => "float" }
}

  fingerprint {
    source => ["doc_key"]
    target => "doc_key_md5"
    method => "MD5"
  }

  mutate {
    add_field => {
      "[@metadata][_id]" => "%{doc_key_md5}"
    }
  }

  date {
    timezone => "Etc/UTC"
    match => ["timestamp", "yyyy-MM-dd HH:mm:ss.SSSSSS"]
    target => "@timestamp"
  }

  mutate {
    remove_field => ["doc_key"]
    add_tag => ["gpu"]
  }
  }
}

output {
if [type] == "worker_node_gpus" {
  opensearch {
   hosts => ""
   cacert => ""
   index => "atlas_panda_worker_node-gpu"
   document_id => "%{[@metadata][_id]}"
   user => ""
   password => ""
   ssl => true
   manage_template => false
  }
  stdout { codec => rubydebug }

}
}
