input {
  jdbc {
    jdbc_driver_library => "/opt/ojdbc8.jar"
    jdbc_driver_class => "Java::oracle.jdbc.OracleDriver"
    jdbc_connection_string => "CONNECTION_STRING"
    jdbc_user => "USER"
    jdbc_password => "PASSWORD"
    id => "a"
    type => "worker_node"



    statement => "
         SELECT
  NVL(wn.SITE, 'UNKNOWN')                      AS SITE,
  NVL(wn.HOST_NAME, 'UNKNOWN')                 AS HOST_NAME,
  NVL(wn.CPU_MODEL, 'UNKNOWN')                 AS CPU_MODEL,

  NVL(wn.N_LOGICAL_CPUS, -1)                   AS N_LOGICAL_CPUS,
  NVL(wn.N_SOCKETS, -1)                        AS N_SOCKETS,
  NVL(wn.CORES_PER_SOCKET, -1)                 AS CORES_PER_SOCKET,
  NVL(wn.THREADS_PER_CORE, -1)                 AS THREADS_PER_CORE,

  NVL(ROUND(wn.total_memory / 1024, 0), -1)    AS memory_GB,
  NVL(ROUND(wn.total_local_disk / 1024, 0), -1) AS disk_TB,

  NVL(wn.CPU_ARCHITECTURE, 'UNKNOWN')          AS CPU_ARCHITECTURE,
  NVL(wn.CPU_ARCHITECTURE_LEVEL, 'UNKNOWN')    AS CPU_ARCHITECTURE_LEVEL,
  NVL(wn.CLOCK_SPEED, -1)                      AS CLOCK_SPEED,

  NVL(wn.TOTAL_MEMORY, -1)                     AS TOTAL_MEMORY,

  NVL(
    TO_CHAR(CAST(wn.LAST_SEEN AS TIMESTAMP), 'YYYY-MM-DD HH24:MI:SS.FF6'),
    'UNKNOWN'
  ) AS LOG_TS,

  NVL(wn.TOTAL_LOCAL_DISK, -1)                 AS TOTAL_LOCAL_DISK,
  NVL(wnq.PANDA_QUEUE, 'UNKNOWN')              AS PANDA_QUEUE

FROM ATLAS_PANDA.WORKER_NODE wn
JOIN atlas_panda.worker_node_queue wnq
  ON wn.site = wnq.site
 AND wn.host_name = wnq.host_name
    "
  }
}

filter {
if [type] == "worker_node" {
  mutate {
    rename => { "log_ts" => "timestamp" }
    add_field => {
      "doc_key" => "%{site}-%{host_name}-%{panda_queue}-%{type}"
    }
  }
mutate {
  convert => { "clock_speed" => "float" }
}

  fingerprint {
    source => ["doc_key"]
    target => "doc_key_md5"
    method => "MD5"
  }

  mutate {
    add_field => {
      "[@metadata][_id]" => "%{doc_key_md5}"
    }
  }

  date {
    timezone => "Etc/UTC"
    match => ["timestamp", "yyyy-MM-dd HH:mm:ss.SSSSSS"]
    target => "@timestamp"
  }

  mutate {
    remove_field => ["doc_key"]
    add_tag => ["cpu"]
  }

  }
}

output {
if [type] == "worker_node" {
  opensearch {
   hosts => ""
   cacert => ""
   index => "atlas_panda_worker_node-cpu"
   document_id => "%{[@metadata][_id]}"
   user => ""
   password => ""
   ssl => true
   manage_template => false
  }

  stdout { codec => rubydebug }
}
}
