filebeat.inputs:
- type: log
  enabled: true
  fields:
    type: prodtask_elk
  paths:
    - /var/log/prodtasklog/json/logfile.prodtask_ELK
  json.keys_under_root: true
  json.add_error_key: true
output.logstash:
  hosts: ["aipanda011:5044"]
  worker: 4
  bulk_max_size : 8192
  loadbalance: true
  compression_level: 3
  index: prodsyslogs
logging.level: info
logging.to_files: true
logging.to_syslog: false
logging.files:
  path: /var/log/filebeat
  name: filebeat.log
  keepfiles: 7
  permissions: 0644
  rotateeverybytes: 10485760