filebeat:
  prospectors:
    -
      #########panda_harvester_stderr#########
      paths:
        - /var/log/harvester/panda_harvester_stderr.log
      input_type: log
      fields:
        type:  harvester_stderr
      multiline.pattern: '#####START#####'
      multiline.negate: true
      multiline.match: after
      multiline.flush_pattern: '#####END#####'
      include_lines: ['#####START#####']
    -
      #########panda-cacher.log#########
      paths:
        - /var/log/harvester/panda-cacher.log
      input_type: log
      fields:
        type: harvester_cacher
      multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
      multiline.negate: true
      multiline.match: after         
    -
      #########panda-commandmanager.log#########
      paths:
        - /var/log/harvester/panda-command_manager.log
      input_type: log
      fields:
        type: harvester_commandmanager
      multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
      multiline.negate: true
      multiline.match: after         
    -
      #########panda-communicator.log#########
      paths:
        - /var/log/harvester/panda-communicator.log
      input_type: log
      fields:
        type: harvester_communicator
      multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
      multiline.negate: true
      multiline.match: after         
    -
      #########panda-communicator_pool.log#########
      paths:
        - /var/log/harvester/panda-communicator_pool.log
      input_type: log
      fields:
        type: harvester_communicatorpool
      multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
      multiline.negate: true
      multiline.match: after         
    -
      #########panda-cred_manager.log#########
      paths:
        - /var/log/harvester/panda-cred_manager.log
      input_type: log
      fields:
        type: harvester_credmanager
      multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
      multiline.negate: true
      multiline.match: after  
    -
      #########panda-db_proxy.log#########
      paths:
        - /var/log/harvester/panda-db_proxy.log
      input_type: log
      fields:
        type: harvester_dbproxy
      multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
      multiline.negate: true
      multiline.match: after         
    -
      #########panda-db_proxy_pool.log#########
      paths:
        - /var/log/harvester/panda-db_proxy_pool.log
      input_type: log
      fields:
        type: harvester_dbproxypool
      multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
      multiline.negate: true
      multiline.match: after         
    -
      #########panda-event_feeder.log#########
      paths:
        - /var/log/harvester/panda-event_feeder.log
      input_type: log
      fields:
        type: harvester_eventfeeder
      multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
      multiline.negate: true
      multiline.match: after         
    -
      #########panda-job_fetcher.log#########
      paths:
        - /var/log/harvester/panda-job_fetcher.log
      input_type: log
      fields:
        type: harvester_jobfetcher
      multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
      multiline.negate: true
      multiline.match: after
    -
      #########panda-master.log#########
      paths:
        - /var/log/harvester/panda-master.log
      input_type: log
      fields:
        type: harvester_master
      multiline.pattern: '#####START#####'
      multiline.negate: true
      multiline.match: after
      multiline.flush_pattern: '#####END#####'
      include_lines: ['#####START#####']
    -
      #########panda-monitor.log#########
      paths:
        - /var/log/harvester/panda-monitor.log
      input_type: log
      fields:
        type: harvester_monitor
      multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
      multiline.negate: true
      multiline.match: after         
    -
      #########panda-multijob_workermaker.log#########
      paths:
        - /var/log/harvester/panda-multijob_workermaker.log
      input_type: log
      fields:
        type: harvester_multijobworkermaker
      multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
      multiline.negate: true
      multiline.match: after
    -
      #########panda-no_voms_cred_manager.log#########
      paths:
        - /var/log/harvester/panda-no_voms_cred_manager.log
      input_type: log
      fields:
        type: harvester_novomscredmanager
      multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
      multiline.negate: true
      multiline.match: after
    -
      #########panda-pilotmover_preparator.log#########
      paths:
        - /var/log/harvester/panda-pilotmover_preparator.log
      input_type: log
      fields:
        type: harvester_pilotmoverpreparator
      multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
      multiline.negate: true
      multiline.match: after         
    -
      #########panda-plugin_factory.log#########
      paths:
        - /var/log/harvester/panda-plugin_factory.log
      input_type: log
      fields:
        type: harvester_pluginfactory
      multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
      multiline.negate: true
      multiline.match: after         
    -
      #########panda-preparator.log#########
      paths:
        - /var/log/harvester/panda-preparator.log
      input_type: log
      fields:
        type: harvester_preparator
      multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
      multiline.negate: true
      multiline.match: after         
    -
      #########panda-propagator.log#########
      paths:
        - /var/log/harvester/panda-propagator.log
      input_type: log
      fields:
        type: harvester_propagator
      multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
      multiline.negate: true
      multiline.match: after         
    -
      #########panda-queue_config_mapper.log#########
      paths:
        - /var/log/harvester/panda-queue_config_mapper.log
      input_type: log
      fields:
        type: harvester_queueconfigmapper
      multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
      multiline.negate: true
      multiline.match: after         
    -
      #########panda-rucio_stager_hpc.log#########
      paths:
        - /var/log/harvester/panda-rucio_stager_hpc.log
      input_type: log
      fields:
        type: harvester_ruciostagerhpc
      multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
      multiline.negate: true
      multiline.match: after
    -
      #########panda-saga_monitor.log#########
      paths:
        - /var/log/harvester/panda-saga_monitor.log
      input_type: log
      fields:
        type: harvester_sagamonitor
      multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
      multiline.negate: true
      multiline.match: after     
    -
      #########panda-saga_submitter.log#########
      paths:
        - /var/log/harvester/panda-saga_submitter.log
      input_type: log
      fields:
        type: harvester_sagasubmitter
      multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
      multiline.negate: true
      multiline.match: after
    -
      #########panda-saga_sweeper.log#########
      paths:
        - /var/log/harvester/panda-saga_sweeper.log
      input_type: log
      fields:
        type: harvester_sagasubmitter
      multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
      multiline.negate: true
      multiline.match: after
    -
      #########panda-shared_file_messenger.log#########
      paths:
        - /var/log/harvester/panda-shared_file_messenger.log
      input_type: log
      fields:
        type: harvester_sharedfilemessenger
      multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
      multiline.negate: true
      multiline.match: after  
    -
      #########panda-stager.log#########
      paths:
        - /var/log/harvester/panda-stager.log
      input_type: log
      fields:
        type: harvester_stager
      multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
      multiline.negate: true
      multiline.match: after         
    -
      #########panda-submitter.log#########
      paths:
        - /var/log/harvester/panda-submitter.log
      input_type: log
      fields:
        type: harvester_submitter
      multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
      multiline.negate: true
      multiline.match: after         
    -
      #########panda-sweeper.log#########
      paths:
        - /var/log/harvester/panda-sweeper.log
      input_type: log
      fields:
        type: harvester_sweeper
      multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
      multiline.negate: true
      multiline.match: after         
    -
      #########panda-watcher.log#########
      paths:
        - /var/log/harvester/panda-watcher.log
      input_type: log
      fields:
        type: harvester_watcher
      multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
      multiline.negate: true
      multiline.match: after  
    -
      #########panda-worker_adjuster.log#########
      paths:
        - /var/log/harvester/panda-worker_adjuster.log
      input_type: log
      fields:
        type: harvester_workeradjuster
      multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
      multiline.negate: true
      multiline.match: after    
    -
      #########panda-worker_maker.log#########
      paths:
        - /var/log/harvester/panda-worker_maker.log
      input_type: log
      fields:
        type: harvester_workermaker
      multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
      multiline.negate: true
      multiline.match: after 
        
  registry_file: /var/lib/filebeat/registry

output.logstash:
  hosts: [""]
  ssl.enabled: true
  ssl.certificate_authorities: "logstash.crt"
  worker: 4
  bulk_max_size : 8192
  #loadbalance: true
  compression_level: 3
  index: harvestertitanlogs

logging:
  level: debug

  to_files: true

  to_syslog: false

  files:
    path: /var/log/filebeat
    name: filebeat.log
    rotateeverybytes: 10485760 # = 10MB
