filebeat.inputs:
#########panda-activator.log#########
- type: log
  enabled: true
  fields:
    type: activatorlog
  paths:
    - /var/log/panda/panda-activator.log
#########panda_server_access#########
- type: log
  enabled: true
  fields:
    type: serveraccess
  paths:
    - /var/log/panda/panda_server_access_log
#########panda_server_error#########
- type: log
  enabled: true
  fields:
    type: servererror
  paths:
    - /var/log/panda/panda_server_error_log
#########panda-broker.log#########
- type: log
  enabled: true
  fields:
    type: brokerlog
  paths:
    - /var/log/panda/panda-broker.log
#########panda_Utils.log#########
- type: log
  enabled: true
  fields:
    type: utils
  paths:
    - /var/log/panda/panda-Utils.log
#########panda-broker_util.log#########
- type: log
  enabled: true
  fields:
    type: brokerutil
  paths:
    - /var/log/panda/panda-broker_util.log
#########panda-UserIF.log#########
- type: log
  enabled: true
  fields:
    type: userif
  exclude_lines: ['DEBUG']
  paths:
    - /var/log/panda/panda-UserIF.log
#########panda-Watcher.log#########
- type: log
  enabled: true
  fields:
    type: watcher
  exclude_lines: ['DEBUG']
  paths:
    - /var/log/panda/panda-Watcher.log
#########panda-PilotRequests.log#########
- type: log
  enabled: true
  fields:
    type: pilotrequest
  paths:
    - /var/log/panda/panda-PilotRequests.log
#########panda-AddProcess.log#########
- type: log
  enabled: true
  fields:
    type: addprocess
  paths:
    - /var/log/panda/panda-add_process.log.log
#########panda-adder.log#########
- type: log
  enabled: true
  fields:
    type: adder
  exclude_lines: ['DEBUG']
  paths:
    - /var/log/panda/panda-adder.log
#########panda-Closer.log#########
- type: log
  enabled: true
  fields:
    type: closer
  exclude_lines: ['DEBUG']
  paths:
    - /var/log/panda/panda-closer.log
#########panda-ConBridge.log#########
- type: log
  enabled: true
  fields:
    type: conbridge
  paths:
    - /var/log/panda/panda-ConBridge.log
#########panda-RunRebro.log#########
- type: log
  enabled: true
  fields:
    type: runrebro
  paths:
    - /var/log/panda/panda-runRebro.log
#########panda-Configurator_DBIF.log#########
- type: log
  enabled: true
  exclude_lines: ['DEBUG']
  fields:
    type: configuratordbif
  paths:
    - /var/log/panda/panda-Configurator_DBIF.log
#########panda-CopyArchive.log#########
- type: log
  enabled: true
  fields:
    type: copyarchive
  paths:
    - /var/log/panda/panda-copyArchive.log
#########panda-DatasetManager.log#########
- type: log
  enabled: true
  fields:
    type: datasetmanager
  exclude_lines: ['DEBUG']
  paths:
    - /var/log/panda/panda-datasetManager.log
#########panda-DBproxypool.log#########
- type: log
  enabled: true
  exclude_lines: ['DEBUG']
  fields:
    type: dbproxypool
  paths:
    - /var/log/panda/panda-DBProxyPool.log
#########panda-DynDataDistributor.log#########
- type: log
  enabled: true
  fields:
    type: dyndatadistributor
  paths:
    - /var/log/panda/panda-DynDataDistributer.log
#########panda-Finisher.log#########
- type: log
  enabled: true
  fields:
    type: finisher
  paths:
    - /var/log/panda/panda-finisher.log
#########panda-Initializer.log#########
- type: log
  enabled: true
  fields:
    type: initialize
  paths:
    - /var/log/panda/panda-Initializer.log
#########panda-Notifier.log#########
- type: log
  enabled: true
  fields:
    type: notifier
  paths:
    - /var/log/panda/panda-Notifier.log
#########panda-PrioryMassage.log#########
- type: log
  enabled: true
  fields:
    type: priorymassage
  paths:
    - /var/log/panda/panda-prioryMassage.log
#########panda-ProcessLimiter.log#########
- type: log
  enabled: true
  fields:
    type: processlimiter
  paths:
    - /var/log/panda/panda-ProcessLimiter.log
#########panda-TaskBuffer.log#########
- type: log
  enabled: true
  exclude_lines: ['DEBUG']
  fields:
    type: taskbuffer
  paths:
    - /var/log/panda/panda-TaskBuffer.log
#########Multiline section###############
#########panda-RetrialModule.log#########
- type: log
  enabled: true
  fields:
    type: retrialmodule
  exclude_lines: ['DEBUG']
  multiline:
    pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
    negate: true
    match: after
  paths:
    - /var/log/panda/panda-RetrialModule.log
#########panda-setupper.log#########
- type: log
  enabled: true
  fields:
    type: setupper
  exclude_lines: ['DEBUG']
  multiline:
    pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
    negate: true
    match: after
  paths:
    - /var/log/panda/panda-setupper.log
########panda-DBProxyFiltered.log######
- type: log
  enabled: true
  fields:
    type: dbproxyfiltered
  multiline:
    pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
    negate: true
    match: after
  paths:
    - /var/log/panda/panda-DBProxyFiltered.log
#########panda-Entry.log#########
- type: log
  enabled: true
  fields:
    type: entry
  exclude_lines: ['DEBUG']
  multiline:
    pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
    negate: true
    match: after
  paths:
    - /var/log/panda/panda-Entry.log
#########panda.log#########
- type: log
  enabled: true
  fields:
    type: pandalog
  multiline:
    pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
    negate: true
    match: after
  paths:
    - /var/log/panda/panda.log
#########panda.add.log#########
- type: log
  enabled: true
  exclude_lines: ['DEBUG']
  fields:
    type: addlog
  multiline:
    pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
    negate: true
    match: after
  paths:
    - /var/log/panda/panda.add

#########panda-recover_lost_files#########
- type: log
  enabled: true
  exclude_lines: ['DEBUG']
  fields:
    type: recoverlostfiles
  multiline:
    pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
    negate: true
    match: after
  paths:
    - /var/log/panda/panda-recover_lost_files.log

#########panda-ProxyCache.log#########
- type: log
  enabled: true
  fields:
    type: proxycache
  paths:
    - /var/log/panda/panda-ProxyCache.log

#########panda-api_data_carousel.log #########
- type: log
  enabled: true
  fields:
    type: pandaapidc
  paths:
    - /var/log/panda/panda-api_data_carousel.log

output.logstash:
  hosts: ["aipanda111:5044", "aipanda112:5044", ]
  worker: 4
  bulk_max_size : 8192
  loadbalance: true
  compression_level: 3
  index: pandalogs
logging.level: info
logging.to_files: true
logging.to_syslog: false
logging.files:
  path: /var/log/filebeat
  name: filebeat.log
  keepfiles: 7
  permissions: 0644
  rotateeverybytes: 10485760
